[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"


